### ISSUE TITLE
I am using boost_1_61_0, and can not build correctly

### ISSUE THREAD

**Issue by xiongzhend** [merlin82/NetMT#1]
m_new_connection->reset(new Connection(this));
 There is no 'reset' function available, what do I miss?

**Comment by merlin82** [comment]
It's boost:shared_ptr. which compiler do you use?
typedef boost::shared_ptr<Connection> ConnectionPtr;

**Comment by xiongzhend** [comment]
I don't know, but after change another pc, it works
